anguage: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - nvm install node
  - node -v
  - npm i yarn
  - yarn  --ignore-engines

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - echo "" >> .env
script:
  - yarn test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
