const types = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    PRODUCTS_FETCH_SUCCESS: "PRODUCTS_FETCH",
    PRODUCTS_FETCH_FAILURE: "PRODUCTS_FETCH_FAILURE",
};

export default types;
